remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [n8n Local Installation Guide]
tagline: [Guide to install n8n locally on Windows, Mac, and Linux]
description: [Guide to install n8n locally on Windows, Mac, and Linux]
